import pathlib
import shutil
import re

def organize_by_pattern(source_dir: str):
    base_path = pathlib.Path(source_dir).resolve()
    
    # Define rules using Regex patterns
    # Logic: r'pattern': 'Target Folder'
    # r'.*CapitalOne' matches any filename containing 'CapitalOne' after any characters
    context_rules = {
        r'.*WeatherTech': '_Automotive_',    
        r'.*Statefarm': 'Insurance',
        r'.*Verizon': 'Utility - Phone',
        r'.*ATT': 'Utility - Phone',        
        r'.*SunPass': 'Utility - Transportation',
        r'.*SUNPASS': 'Utility - Transportation',
        r'.*Uber': 'Utility - Transportation',       
        r'.*UBER': 'Utility - Transportation',         
        r'.*FPL': 'Utility - Electric',
        r'.*Spectrum': 'Utility - Internet',
        r'.*CapitalOne': 'Financial',        
        r'.*Crypto': 'Financial',
        r'.*Mohela': 'Financial',
        r'.*StudentLoans': 'Financial',
        r'.*Student_Loans': 'Financial',
        r'.*Student_Loan': 'Financial',        
        r'.*TruckPayment': 'Financial',  
        r'.*Truck_Payment': 'Financial',         
        r'.*TD_Auto': 'Financial',  
        r'.*TDAuto': 'Financial',   
        r'.*401k': 'Financial',       
        r'.*Optum': 'Financial',  
        r'.*HSA': 'Financial',         
        r'.*_Python_': '_Employment_',  
        r'.*_PYTHON_': '_Employment_', 
        r'.*LINKEDIN': '_Employment_',     
        r'.*LinkedIn': '_Employment_',         
        r'.*JOBSCAN': '_Employment_',  
        r'.*_JAVA_': '_Employment_',        
        r'.*UniversityOfPhoenix': '_Employment_', 
        r'.*UOPX': '_Employment_',         
        r'.*US_HEALTHGroup_INSURANCE': 'Insurance', 
        r'.*Progressive': 'Insurance',         
        r'.*Wallet': 'Expense - Accessories',        
        r'.*TSHIRT': 'Expense - Apparel',
        r'.*Tshirt': 'Expense - Apparel', 
        r'.*TShirt': 'Expense - Apparel',   
        r'.*_TShirt_': 'Expense - Apparel',   
        r'.*Oneils': 'Expense - Apparel',        
        r'.*Metallica': 'Expense - Apparel',
        r'.*Apparel': 'Expense - Apparel', 
        r'.*TommyBahamma': 'Expense - Apparel',        
        r'.*CarbonCobalt': 'Expense - Apparel', 
        r'.*Carbon2Cobalt': 'Expense - Apparel',         
        r'.*TommyBahamma': 'Expense - Apparel', 
        r'.*_Boston_Scally_': 'Expense - Apparel',    
        r'.*CargoShorts': 'Expense - Apparel',  
        r'.*TrueWerk': 'Expense - Apparel',        
        r'.*Amazon': 'Expense - Amazon',        
        r'.*Apartment': 'Expense - Apartments',
        r'.*APARTMENT': 'Expense - Apartments',        
        r'.*Rent': 'Expense - Apartments',  
        r'.*RENT': 'Expense - Apartments',  
        r'.*Timacuan': 'Expense - Apartments',         
        r'.*BaseballCards': 'Expense - Collectible',
        r'.*BaseballCard': 'Expense - Collectible',        
        r'.*PeteRose': 'Expense - Collectible',
        r'.*_PeteRose_': 'Expense - Collectible', 
        r'.*_PeteRose_Signed_': 'Expense - Collectible',         
        r'.*Comics': 'Expense - Collectible',      
        r'.*Comicbook': 'Expense - Collectible', 
        r'.*ComicBook': 'Expense - Collectible', 
        r'.*ComicBooks': 'Expense - Collectible',
        r'.*CGC_Submittal': 'Expense - Collectible', 
        r'.*CGC_SubmitForGrading': 'Expense - Collectible',        
        r'.*CGC_invoice': 'Expense - Collectible',     
        r'.*CGC_Second': 'Expense - Collectible',   
        r'.*CGC_Payment': 'Expense - Collectible',   
        r'.*CGC_Member': 'Expense - Collectible',   
        r'.*CGC_Shipping': 'Expense - Collectible',         
        r'.*Spiderman': 'Expense - Collectible', 
        r'.*AmericanSilverEagle': 'Expense - Collectible',    
        r'.*American_Eagles': 'Expense - Collectible',         
        r'.*BoneValley_Excursion_': 'Expense - Excursions', 
        r'.*BoneValleyFossil': 'Expense - Excursions',   
        r'.*_Cubs_': 'Expense - Excursions',   
        r'.*Kitchen': 'Expense - Home', 
        r'.*kitchen': 'Expense - Home',     
        r'.*HOBBY': 'Expense - Leisure',   
        r'.*hobby': 'Expense - Leisure',        
        r'.*Movie': 'Expense - Movies',
        r'.*MOVIE': 'Expense - Movies',
        r'.*Meal': 'Expense - Meals',
        r'.*MEAL': 'Expense - Meals',
        r'.*Giovanni': 'Expense - Meals',  
        r'.*Pizza': 'Expense - Meals',      
        r'.*PIZZA': 'Expense - Meals',          
        r'.*French_Roast_Chicory': 'Expense - Meals',  
        r'.*Coffee': 'Expense - Meals',     
        r'.*French_Wink': 'Expense - Meals',          
        r'.*SecretLab': 'Expense - Office',   
        r'.*desk': 'Expense - Office',         
        r'.*Desk': 'Expense - Office',  
        r'.*CanlessAir': 'Expense - Office',    
        r'.*_CanlessAir': 'Expense - Office',      
        r'.*PersonalCare': 'Expense - Personal Care',    
        r'.*Personalcare': 'Expense - Personal Care',       
        r'.*personalcare': 'Expense - Personal Care',         
        r'.*Molekule': 'Expense - Personal Care',
        r'.*Hair': 'Expense - Personal Care',        
        r'.*Shampoo': 'Expense - Personal Care',
        r'.*BrioGeo': 'Expense - Personal Care',        
        r'.*Barber': 'Expense - Personal Care',  
        r'.*BARBER': 'Expense - Personal Care',  
        r'.*Weight Loss': 'Expense - Personal Care', 
        r'.*WeightLoss': 'Expense - Personal Care',     
        r'.*Supplements': 'Expense - Personal Care',           
        r'.*ShowerHead': 'Expense - Personal Care',       
        r'.*Exfoliating': 'Expense - Personal Care',     
        r'.*Shoes': 'Expense - Personal Care',  
        r'.*Socks': 'Expense - Personal Care',   
        r'.*ORTHOFeet': 'Expense - Personal Care', 
        r'.*ORTHOFEET': 'Expense - Personal Care',    
        r'.*Beard': 'Expense - Personal Care',     
        r'.*Brush': 'Expense - Personal Care',  
        r'.*HandSoap': 'Expense - Personal Care',  
        r'.*Waist_Trimmer': 'Expense - Personal Care',         
        r'.*Storage': 'Expense - Relocation', 
        r'.*MoveOutOfStorage': 'Expense - Relocation', 
        r'.*ExtraStorage': 'Expense - Relocation',      
        r'.*SIDIO': 'Expense - Relocation',
        r'.*Sidio': 'Expense - Relocation',
        r'.*UHAUL': 'Expense - Relocation',
        r'.*UHaul': 'Expense - Relocation',       
        r'.*Uhaul': 'Expense - Relocation',         
        r'.*Extended_Stay': 'Expense - Relocation',    
        r'.*EXTENDED_STAY': 'Expense - Relocation', 
        r'.*WoodSprings_Suites': 'Expense - Relocation', 
        r'.*WoodSpring Suites': 'Expense - Relocation',     
        r'.*Change of Address': 'Expense - Relocation',        
        r'.*Change Of Address': 'Expense - Relocation',    
        r'.*Change_Of_Address': 'Expense - Relocation', 
        r'.*Streaming': 'Expense - Streaming',
        r'.*SiriusXM': 'Expense - Streaming',        
        r'.*CANON_Printer': 'Expense - Technology',  
        r'.*Canon_Printer': 'Expense - Technology',      
        r'.*ATARI_2600': 'Expense - Technology', 
        r'.*ATARI': 'Expense - Technology',         
        r'.*Computer': 'Expense - Technology', 
        r'.*DELL': 'Expense - Technology',    
        r'.*Dell': 'Expense - Technology',   
        r'.*WebCam': 'Expense - Technology',
        r'.*Alienware': 'Expense - Technology', 
        r'.*Nested_Domain': 'Expense - Technology',   
        r'.*IONOS': 'Expense - Technology',  
        r'.*Movavi': 'Expense - Technology',    
        r'.*Malwarebytes': 'Expense - Technology',    
        r'.*MalwareBytes': 'Expense - Technology',  
        r'.*_MalwareBytes_': 'Expense - Technology',         
        r'.*Travel': 'Expense - Travel', 
        r'.*TRAVEL': 'Expense - Travel',
        r'.*Hotel': 'Expense - Travel',
        r'.*HOTEL': 'Expense - Travel',  
        r'.*HolidayInnExpress': 'Expense - Travel',  
        r'.*Holiday_INN_Express': 'Expense - Travel',          
        r'.*Home2Suites': 'Expense - Travel',     
        r'.*Marriot': 'Expense - Travel',     
        r'.*LA_QUINTA': 'Expense - Travel',         
        r'.*TripToPhoenix': 'Expense - Travel',
        r'.*KEYWestTrip': 'Expense - Vacation',    
        r'.*KeyWestTrip': 'Expense - Vacation',         
        r'.*CanadaTrip': 'Expense - Vacation',        
        r'.*TripToVegas': 'Expense - Vacation',          
        r'.*HamptonInn': 'Expense - Vacation',  
        r'.*Smokies_Trip': 'Expense - Vacation',
        r'.*Great_Smokies': 'Expense - Vacation',    
        r'.*Biltmore_House': 'Expense - Vacation',         
        r'.*EuropeTrip': 'Expense - Vacation',  
        r'.*EuropeanTrip': 'Expense - Vacation',  
        r'.*EuroStar': 'Expense - Vacation',     
        r'.*Norse Atlantic Airways': 'Expense - Vacation', 
        r'.*Paris_': 'Expense - Vacation',        
        r'.*Glenfinnan Viaduct': 'Expense - Vacation',      
        r'.*Louvre': 'Expense - Vacation', 
        r'.*Train_North': 'Expense - Vacation',   
        r'.*TrainNorth': 'Expense - Vacation',        
        r'.*Monument_Excursion': 'Expense - Vacation',   
        r'.*IRS_Amount': 'Taxation Without Representation',     
        r'.*IRS_Payment': 'Taxation Without Representation',
        r'.*IRS_Tax': 'Taxation Without Representation', 
        r'.*_IRS_': 'Taxation Without Representation',         
        r'.*TurboTax': 'Taxation Without Representation',         
    }

    for item in base_path.rglob('*'):
        # Ensure we only process files and ignore the script itself or target folders
        if item.is_file() and item.suffix.lower() not in ['.py', '.sh']:
            moved = False
            
            for pattern, folder_name in context_rules.items():
                # re.IGNORECASE makes it resilient to 'capitalone' vs 'CapitalOne'
                if re.search(pattern, item.name, re.IGNORECASE):
                    dest_folder = base_path / folder_name
                    dest_folder.mkdir(parents=True, exist_ok=True)
                    
                    dest_path = dest_folder / item.name
                    
                    if not dest_path.exists():
                        try:
                            shutil.move(str(item), str(dest_path))
                            print(f"Success: {item.name} -> {folder_name}/")
                            moved = True
                            break 
                        except Exception as e:
                            print(f"Error moving {item.name}: {e}")
            
            if not moved:
                # Optional: Handle files that don't match any pattern
                pass

if __name__ == "__main__":
    # Use the current directory or provide a specific path
    organize_by_pattern('.')